UserBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        name:
            type: string
            length: 255
        firstname:
            type: string
            length: 255
        picture:
            type: string
            length: 255
        age:
            type: integer
    manyToMany:
        events:
            targetEntity: AppBundle\Entity\Event
            inversedBy: user
            joinTable:
                name: events_users
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    event_id:
                        referencedColumnName: id

    lifecycleCallbacks:
          prePersist: [ preUpload, setCreatedAtValue, setExpiresAtValue ]
          preUpdate: [ preUpload, setUpdatedAtValue ]
          postPersist: [ upload ]
          postUpdate: [ upload ]
          postRemove: [ removeUpload ]