AppBundle\Entity\Event:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\EventRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        picture:
            type: string
            length: 255
        price:
            type: integer
        name:
            type: string
            length: 255
        heart:
            type: boolean
    manyToMany:
        events:
            targetEntity: UserBundle\Entity\User
            inversedBy: user
            joinTable:
                name: events_users
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    event_id:
                        referencedColumnName: id
        users:
            targetEntity: AppBundle\Entity\Event
            mappedBy: events
    lifecycleCallbacks:
          prePersist: [ preUpload, setCreatedAtValue, setExpiresAtValue ]
          preUpdate: [ preUpload, setUpdatedAtValue ]
          postPersist: [ upload ]
          postUpdate: [ upload ]
          postRemove: [ removeUpload ]